### ISSUE TITLE
Add opt-in field to all r-things

### ISSUE THREAD

**Issue by lolownia** [WeMoveEU/speakcivi#1]
I will add it on speakout site, configurable. But it must be synced to some kind of opt-in field in CiviContact. This will implement the one-stage opt-in on petition site.

For double opt-in we are still brainstorming.

**Comment by tttp** [comment]
so what we did for double opt-in:
we don't send any email from speakout
when we add a contact on civi via this bsd extension, we create the contact+action "petition sign"+add them to a "activist" group with the status pending+sending an email "click here to confirm+link to a confirm page"
beside the BSD like api endpoint, this extension provides that confirm page

It has too many hardcoded stuff and assumptions, but that won't be long to be made more generic

X+

**Comment by lolownia** [comment]
@tttp Any new ideas regarding this issue?

Could we have a scenario when contacts are added as _pending_ but email is sent by speakout, with confirmation link placeholder leading to civicrm?

**Comment by tttp** [comment]
so now everything is done on the civi side, the rationale is that what email to send depends if the email has already been confirmed previously or is new, and that information is only in civicrm
