### ISSUE TITLE
Current date of Leave

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/speakcivi#117]
Date of Leave is provided by logs on contacts (tab *Change log* on view contact page). Everything would have been great If all actions reported in log. But they aren't.

Better solution: current date (date when action API Speakcivi.leave runs).

**Comment by tttp** [comment]
better indeed, the aim of using the change log was to handle historical
data.

And in general: try creating the leave when we know more about it, eg if we
can know the reason to opt-out, let's put it and put the campaign_id too.

If not, the "catch all" method is fine using the time when it runs
