### ISSUE TITLE
save the medium on the rshare action

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#129]
right now, we have lots of "duplicate" shares, eg contact 576527, it might be that our members share on a lot of different channels... or that we need to dedupe...

**Comment by scardinius** [comment]
saving the medium is already implemented.
https://github.com/WeMoveEU/speakcivi/blob/master/CRM/Speakcivi/Page/Speakcivi.php#L212

**Comment by tttp** [comment]
https://www.wemove.eu/civicrm/activity?atype=54&action=view&reset=1&id=2102469&cid=576527&context=activity&searchContext=activity

where? medium should be facebook or twitter or whatsapp, I don't see it

**Comment by scardinius** [comment]
section "action_source", field "medium"

**Comment by tttp** [comment]
We are talking about two different things:
I'm not talking about the utm params on where the contact comes from, I am talking about what is the rshare action done (eg. does she click on the twitter button or facebook or..)

**Comment by scardinius** [comment]
ok. I found field rshares.medium on speakout db. Are you talking about this field?

on params we don't have such field, https://github.com/WeMoveEU/speakcivi/blob/master/CRM/Speakcivi/Page/Speakcivi.php#L54

**Comment by scardinius** [comment]
ok, so I will prepare speakcivi to support such new data structure in params. On civicrm side will be new custom group named **rshare** for activities. This will also helps #130 

```javascript
params :
{
  action_type : 'share',
  action_technical_type ...
  ...
  rshares : {
    medium : 'facebook', // email, whatsapp, twitter...
    tracking_code : 'qwerty12345'
  }
}
```

Looks ok?

**Comment by scardinius** [comment]
Tested, Implemented on prod
