### ISSUE TITLE
save the tracking_code on rshare

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#130]
so we can see who brought new signatures (the hash in the share is the campaign on the "converted" sign)

it probably needs changes both on speakout (so it's sent) and here (to add it)

**Comment by scardinius** [comment]
Tracking code is implemented already by PR #131

**Comment by scardinius** [comment]
Structure was changed to:

```js
{
    "action_type":"share",
    /* other fields... */
    "metadata":{
        "tracking_codes":{
            "utm_source":"member",
            "utm_medium":"facebook",
            "utm_campaign":"NzvyEem4s5"
        }
    }
}
```

**Comment by tttp** [comment]
Where is it saved on civi?

On 22 September 2016 at 13:18, Tomasz Pietrzkowski <notifications@github.com

**Comment by scardinius** [comment]
To custom group for activity share.

**Comment by rthouvenin** [comment]
The change is done on speakout side, and this morning I imported all the historical data from Speakout.
