### ISSUE TITLE
Creating way too many bounce activities

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#138]
So we were supposed to create activities for BOUNCE events.

We don't filter them properly enough, and we created  278768 "bounce" activities, by incorrectly handing open and sent events as bounce

Fix:
1) filter out to only record bounce events, not all events
2) on the rabbitMQ consumer, process directly the sent events, don't push them further to the "normal" speakout
3) delete all the bounce activities that are sent or open (stored as the subject of the activity)

I'm setting up a clone of civi on lem, if you need to test big requests...

**Comment by scardinius** [comment]
https://github.com/WeMoveEU/uk.co.compucorp.civicrm.mailjet/issues/7
