### ISSUE TITLE
change repository name on speakcivi

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/speakcivi#20]
1. change all strings `bsd`, `bsd_api` or `speakout` into `speakcivi`
  * classes
  * api
  * urls in xml
2. change repository name
3. reinstall on prod
4. change urls on speakout

**Comment by tttp** [comment]
Yes to all of that, but let's do that next week, right now we are with a
live campaign and want to make the updates as uneventful as possible ;)

**Comment by scardinius** [comment]
ok @tttp , I will wait for your sign to start :-)

**Comment by scardinius** [comment]
1. DONE
5. install redirect module - DONE

I'm ready to go on and I'm waiting for your sign.

**Comment by tttp** [comment]
go!
