### ISSUE TITLE
Implement sync of rdonation ?

### ISSUE THREAD

**Issue by lolownia** [WeMoveEU/speakcivi#22]
Could we implement syncing rdonation and rpayu (the one we use with PayU payment processor) so that it creates proper data in civicrm (also in "transactions" in Civi)?

**Comment by tttp** [comment]
not in our todo, we make the donations directly in civi, but PR welcome (cf comment about PHP and @lolownia ;)

**Comment by tttp** [comment]
lolownia, that won't be hard, but let's wait until we get the new api format working for speakout
