### ISSUE TITLE
Rsign with comment sent to civicrm

### ISSUE THREAD

**Issue by lolownia** [WeMoveEU/speakcivi#24]
could Rsign comment be also synced in activity description (or somewhere else if it makes more sense)?

**Comment by tttp** [comment]
@lolownia, could you fix speakout so it pushes
- the optional question/answer
- the comment?

I didn't see them on the calls, so no data in, no data out ;)

**Comment by tttp** [comment]
done, added as the detail of activity
... you need to adapt speakout so it pushes this information, to be checked how it works with the new api format

**Comment by lolownia** [comment]
you have implemented the API in https://github.com/the-open/speakout/issues/40
so metadata { sign_boolean, sign_answer, sign_comment } 
correct?
