### ISSUE TITLE
text for the confirmation email and adapt it

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/speakcivi#26]
@tttp :
we need to generate the text for the confirmation email and adapt it, for instance to create the share and tweet, but it's a pain to do by hand and if you could look at one existing email and imaging a way to generate the message automatically

(a dumb static html form with text+url campaign + a bit of javascript would be good enough for now probably or whatever the easiest

**Comment by scardinius** [comment]
@tttp What do you think about such solution:

* give up Message Temlates and `optin message id` custom value
* template in smarty engine
* templates/CRM/Bsd/Page/Confirm.`{$language}`.`{$format}`.tpl
* `$language` like a en_GB, de_DE, it_IT
* `$format`: text | html
* each language has own template in both format
* in smarty template we can prepare links and combine with special fields.

What we have to decide:
* where to place forward text?
* where to place url to speakout petition?
* where to place twitter text?

I think above fields can be also placed in campaign as a custom fields.

**Comment by tttp** [comment]
Good suggestion, but I'm not sure it would work as so far, each campaign
has a different message (it's always confirm+share, but mixed with some
context "we have 24 hours, thanks you to help the refugee...")

So it needs to be specific for each campaign

This being said, It would be super useful as a workaround to create the
template message as a clone of the default one and associate it with the
campaign

As the second step, creating a page "confirmation email composer"
/civicrm/speakcivi/msg where you have a few fields (url of the campaign,
message for twitter, message for the email) that would automatically
compose the text (all javascript)

then let them copy paste, or add a bit of ajax to automatically save the
updated message

**Comment by scardinius** [comment]
I think a page "confirmation email composer" has the same pros and cons like a current solution - message template editor.

Current management places:
  1. speakout edit form
  2. campaign edit form on CiviCRM
  3. message template editor on CiviCRM or "Confirmation email composer"

New variables:
* Message for the email
* Forward text message
* Url of the campaign
* Message for twitter

Obsolete variables:
* optin message id

Each of those new variables can be moved to custom fields of campaign with default values plain text field. 

Then we can give up the one page with template editor (number 3.). Message template page is not prepared for long list of a templates - each language version of campaign has own template. We have only 15 templates now but this quantity will be rise fast.

Pros:
* safe template - only IT can modify template, especially HTML
* only two places for setting campaigns
* fast setting text fields - plain format is easier than rich text format

Cons:
* IT assistance is necessary in case of a new language

What do you think?

**Comment by tttp** [comment]
hey,

not a bad idea at all to put the message and subject in the campaign. the
assumption that it was the same between campaigns is bogus.

still think a campaign editor is good, to help building the share links and
and twitter and so on

**Comment by scardinius** [comment]
To sum up:

Custom fields in speakout integration:
* Language ("en_GB")
* Sender email (""Xavier - WeMove.EU" <info@wemove.eu>")
* Subject mail ("You are almost done - please confirm your action")
* Message for the email
* Forward text message
* Message for twitter
* utm_campaign code
* Url of the campaign
  * if `null` url based on `external_id`
* HTML Content (whole message) - view only
* TEXT Content (whole message based on HTML content) - view only

The assumption:
* give up Message Temlates and optin message id custom value
* templates/CRM/Bsd/Page/Confirm.{$language}.tpl in HTML format
* $language like a en_GB, de_DE, it_IT
* Text format based on HTML format, strip tags etc.
* static templates are used only for preparing whole content of email and is saved into custom fields
* on page "confirmation email composer" is HTML editor field with content compiled from templates and custom fields. Campaigner can modify it.

Steps:
  1. creating campaign in speakout
  2. testing signature in order to create default campaign in civicrm
  3. edit campaign in civicrm, especially custom fields (utm_campaign, url etc.)
  4. review, edit and save HTML Content on "confirmation email composer"

Ready to go :)

@tttp What do you think?

**Comment by tttp** [comment]
hi,

 the template is going to be different for each campaign, and the
campaigners should be able to change it, could you give me an example of
what stuff should be in the tpl

some of the data is already in speakout, we need to fetch them
automatically. i'm looking into adding an api to make it possible, but for
now assume they will be a way to get that out and fill it

**Comment by scardinius** [comment]
Example is here https://github.com/WeMoveEU/speakcivi/blob/cd0989c2301b183075377ef6fcb4986e4e4bed3f/templates/CRM/Speakcivi/Page/Confirm.en_GB.tpl

* `$url_campaign` - custom fields
* `$url_campaign_fb` - generated by extension based on `$url_campaign`
* `$url_confirm` - generated by extension
* `$utm_campaign` - custom fields
* `$message_twitter` - custom fields
* `$message_top` - custom fields
* `$message_forward_top` - custom fields
* `$message_forward_middle` - custom fields

Such compiled templated will be content of message which can be modify by user at page "confirmation email composer" and saved into special view only custom fields `HTML Content`.

What do you think?

**Comment by tttp** [comment]
@scardinius now the rest json for the campaign contains extra fields (internal name, twitter message), so it will be easier to sync with civi. probably better as a new issue actually ;)

and definitely, using message templates is such a pain, can you create the custom fields needed directly on the campaign so we don't have to use message templates anymore?

**Comment by scardinius** [comment]
And what about field `utm_campaign`? Can be retrieved from rest json?

Of course, new solution without using message templates :)

**Comment by tttp** [comment]
utm_X parameters for the links we generate on the share can be generated directly (eg utm_medium=mail, utm_source=optin, utm_campaign=slug or campaign id

So I would suggest to focus first on adding the needed fields on the campaign as custom fields (eg  moving the message template into campaign as a new field)

For now, don't try to generate automatically the links, we can find a way later on (eg adding a bit of magic in the campaign edit form), but have two separate fields for the message body (optin vs thank you) and two separate fields for the message subject (opt-in vs thank you) and be sure speakout uses properly these fields (the fallback to message id might not be needed, cleaning the existing running campaigns might be easier and all to get rid of some of the code probably). your call.

**Comment by scardinius** [comment]
I'm happy I can close this issue :-)

**Comment by tttp** [comment]
the utm campaign can stay how it is, or concatenate speakout and id

**Comment by scardinius** [comment]
ok, added.
