### ISSUE TITLE
postal_code valid length

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/speakcivi#43]
example zip: `[de] 48329 Havixbeck` generated error like this below:

`Error in call to Address_create : Value for postal_code is 15 characters  - This field has a maxlength of 12 characters.`

todo:
* trim to 12 characters
* check others fields in terms of validation

**Comment by tttp** [comment]
Well spotted, thanks

X+

**Comment by scardinius** [comment]
thx, done.
