### ISSUE TITLE
need more sql for the dataviz

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#45]
@scardinius could you write a new .sql (to be put into the queries folder) that select activities group by

(activity day, campaign, type, status)

I'll do (or we can try doing it together if you want to learn) a dataviz for that. It's likely to move, but would give a better view than the actual one

**Comment by scardinius** [comment]
Yes, I could.

I always want to learn :)

Do you mean one query with such columns?

**Comment by tttp** [comment]
I meant group by, but they are all going to be select too

And not sure at all how to best do that, but we need to distinguish between
new contacts (ie. that came through the campaign) and existing ones.

so if the user is created at the same time as a petition signature,  she is
"new", ideally, the share is "new" too.

We can massage the data on the client side too (that's what I did to
identify the news on the latest_activities) but the data should be

day|campaign|activity type|new?|total
-------------------------------------
09/04/2016|42|signature|new|200
09/04/2016|42|signature|existing|1041
09/04/2016|42|share|existing|384
09/04/2016|42|share|new|10
09/04/2016|44|...
10/04/2016|...

We have been circling around it for a while now, I wonder if now is the
time to realise we really need a campaign_id on the contact table (but I'd
love to be proven wrong and that we don't need it)...

X+

**Comment by scardinius** [comment]
`indicator2` = `NEW` - user created during last 10 minutes.

Such definition allows to sign as NEW share activity.

@tttp Could you review the sql?

**Comment by tttp** [comment]
new isn't about "right now" but "new at the time of the activity" ;(

**Comment by scardinius** [comment]
Yes, new at the time of the activity and I think this is a good approach because the report will return the same result despite of a different time of run the report.
