### ISSUE TITLE
custom token for confirmation hash

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#46]
We have a fair bit of contacts that haven't confirmed their action (that never clicked on the link), we need to be able to send them an email again to remind them to confirm

In order to do that, we need to generate the hash for the confirmation email (as done in the api sendConfirm), but do do that in a custom token, so campaigners can use it in their "reminder" mailing

they are two hooks to use, check out this example:
http://wiki.civicrm.org/confluence/display/CRMDOC/Customized+%28and+Custom%29+Tokens

suggested name for the token "confirmation hash"

They will use it in their mail:

Hey {contact.firstname},
you didn't click on the opt-in link, here is it again, please click so we can contact you again:
https://example.org/civicrm/speakcivi/confirm?id={contact.contact_id}&hash={contact.confirmation_hash}

@scardinius you need to verify that the confirm page works without aid or campaign id (we can put the language to use as an extra param if needed)

FYI: It will likely be used to automate that mailing in a not so distant future (eg. if not confirmed after 48 hours, send the reminder)

**Comment by scardinius** [comment]
Done, tested and implemented on production :)
