### ISSUE TITLE
Take into account the gender param

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#58]
You *might* have an extra param gender on new signatures

the format is [M] or [F] stuffed at the end of the last name.
Can you use them so 
1) it's removed from the last name
2) set gender_id correctly
3) set the prefix (mr ms?)
4) set the email salutation
This one is going to be trickier as it's based on the language, if german:
F->Liebe first+last
M->Lieber first+last
not defined->Hallo first+last
I need to specify further for other languages

@omoldenhauer can you confirm that for german, we use first+last in the salutation?
I'm asking the campaigners about how to address in other languages

**Comment by scardinius** [comment]
Prepared PR #64 
Next step -> clear database

**Comment by scardinius** [comment]
README.md was updated for those changes
