### ISSUE TITLE
When campaign is auto-created contacts are created as opted out

### ISSUE THREAD

**Issue by lolownia** [WeMoveEU/speakcivi#61]
i think when there is no external id set and the campaign is automatically created (where does it take the nems from, b/c they seem to be some wemove campaign names), the contacts created are opted out regardless of optin/out settings should issue that

**Comment by tttp** [comment]
@lolownia the campaign is normally automatically created at the first signature, with whatever info you have on rsign. 

Do you have the latest version of speakcivi?

**Comment by lolownia** [comment]
NowI have, but I get a lot of people who are opted out from mailing, and i think much more then clicked unsubscribe

**Comment by scardinius** [comment]
@lolownia Contact is set up as `NO BULK EMAILS (User Opt Out)` only by one action: click on optout link in confirmation email
https://github.com/WeMoveEU/speakcivi/blob/master/CRM/Speakcivi/Page/Optout.php#L12

Whereas parameter `optIn` is used for sending confirmation email (default value `1`) or NOT sending such email (value `0`). And for activity status.
https://github.com/WeMoveEU/speakcivi/blob/master/CRM/Speakcivi/Page/Speakcivi.php#L174
This optIn parameter can be set up on `Speakcivi API Settings` page.

I hope this explanations are useful.
