### ISSUE TITLE
Improve the share action

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#62]
they are two extra params to save:

"medium":"facebook","tracking_code":"NJcEMJZAsw"
I suggest we just put them into the activity subject, eg "facebook #NJcEMJZAsw"

**Comment by scardinius** [comment]
I tested params for sharing actions such as medium or tracking_code aren't available here https://github.com/WeMoveEU/speakcivi/blob/master/CRM/Speakcivi/Page/Speakcivi.php#L188

Do you plan to add them?

My proposal: add new custom group of fields UTM for activity with fields: 
* utm_source, 
* utm_medium, 
* utm_campaign.

What do you think about this?

**Comment by tttp** [comment]
ok, let's way until we switch (early next year?!) to the new speakout version

**Comment by scardinius** [comment]
Already done
https://github.com/WeMoveEU/speakcivi/blob/master/CRM/Speakcivi/Page/Speakcivi.php#L201
