### ISSUE TITLE
Add contact to language version of group and tag

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/speakcivi#66]
Each contact supposed to be a member of:

* `LANGUAGE speaking activists` group
* `can speak LANGUAGE` tag

In SpeakCivi `group` is determined by `name`. Available groups:

* German language Activists
* English language Activists
* Spanish language Activists
* French language Activists
* Italian language Activists
* Polish Language Activists
* Romanian language Activists

In SpeakCivi `tag` is determined by `name` - not yet created.

@omoldenhauer Could you verify those assumptions?

**Comment by tttp** [comment]
@scardinius,

you can change the name of each group (hidden internal name) that is
different from the label (what the end user sees and can modify)

Please use these "machine" names, and rename them so they are coherent with
what you want, eg speakout-es speakout-de or whatever that makes it easy
and robust to find, and won't get broken next time a user changes the group
name

**Comment by scardinius** [comment]
@tttp Your proposal looks good :-) 

What in situation when such group doesn't exist? Creating or skipping? I think skipping is better because in CiviCRM will not be groups created by api.

**Comment by glilienthal** [comment]
Looks good. I like the idea of having more "can speak language" tags than just English. 
For the Groups: We have one more group called "other speaking members" - Where we should place everybody else. 
Can you make sure the "can speak language" flags are set for the existing members as well?

**Comment by glilienthal** [comment]
One more comment: You write "every contact". I'd say "every member" (i.e. everyone in the group "members")

Makes sense?

**Comment by scardinius** [comment]
To sum up:

Each contact in group `Members` supposed to be a member of:

* `LANGUAGE language Activists` group
* `can speak SHORTCUT-LANGUAGE` tag

In SpeakCivi `group` is determined by `name`. Available groups:

title | name (internal, not updated yet, not visible from CiviCRM)*
--- | ---
German language Activists | de-language-activists
English language Activists | en-language-activists
Spanish language Activists | es-language-activists
French language Activists | fr-language-activists
Italian language Activists | it-language-activists
Polish Language Activists | pl-language-activists
Romanian language Activists | ro-language-activists

*Only IT team can update this value! Remember about this when you will be creating new one or changing names.

In SpeakCivi `tag` is determined by `name` - not yet created. 

* Format: `can speak SHORTCUT-LANGUAGE` - this is necessary to find out proper tag by shortcut
* Examples: `can speak en`, `can speak de`

If language can't be determined or there isn't proper group/tag then we use default group/tag. Defaults:

* default group: `Other speaking Activists`
* default tag: `can speak any language` (not created, different?)

**Comment by omoldenhauer** [comment]
Re: [speakcivi] Add contact to language version of group and tag (#66)


default tag if no language = none. 

o.

Hello scardinius,

Tuesday, December 8, 2015, 12:32:48 PM, you wrote:





To sum up:
Each contact in group Members supposed to be a member of:


LANGUAGE language Activists group
can speak SHORTCUT-LANGUAGE tag

In SpeakCivi group is determined by name. Available groups:



title

name (internal, not updated yet, not visible from CiviCRM)*


German language Activists
de-language-activists


English language Activists
en-language-activists


Spanish language Activists
es-language-activists


French language Activists
fr-language-activists


Italian language Activists
it-language-activists


Polish Language Activists
pl-language-activists


Romanian language Activists
ro-language-activists


*Only IT team can update this value! Remember about this when you will be creating new one or changing names.
In SpeakCivi tag is determined by name - not yet created. 


Format: can speak SHORTCUT-LANGUAGE - this is necessary to find out proper tag by shortcut
Examples: can speak en, can speak de

If language can't be determined or there isn't proper group/tag then we use default group/tag. Defaults:


default group: Other speaking Activists
default tag: can speak any language (not created, different?)

—
Reply to this email directly or view it on GitHub.





-- 
Oliver Moldenhauer
Founding Director
WeMove.EU
+49 177 306 8911
oliver@wemove.eu
skype: olivermoldenhauer

**Comment by scardinius** [comment]
Updated comment https://github.com/WeMoveEU/speakcivi/issues/66#issuecomment-162856589

**Comment by scardinius** [comment]
#69 tested on dev branch, merged, pulled on master :-)
