### ISSUE TITLE
Please add more validation and report errors on bad data (like missing bsd_cons)

### ISSUE THREAD

**Issue by lolownia** [WeMoveEU/speakcivi#67]
instead of doing random things (like creating an activity for a random person) like: https://apps.akcjademokracja.pl/owncloud/index.php/s/Bhu7daqqplqDZUp

**Comment by tttp** [comment]
We can't reproduce the bug on this side. I thought it was solved with sending the right information?

do you have an example of data sent that caused the problem?

**Comment by scardinius** [comment]
I think this issue expired :-)
