### ISSUE TITLE
 Call to a member function getTimezone() on boolean

### ISSUE THREAD

**Issue by lolownia** [WeMoveEU/speakcivi#68]
2015/12/08 14:50:06 [error] 4753#0: *2385689 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getTimezone() on boolean in /home/www/wordpress/wp-content/plugins/civicrm/civicrm/extensions/speakcivi/CRM/Speakcivi/Page/Speakcivi.php on line 790" while reading response header from upstream, client: 188.165.176.227, server: www.akcjademokracja.pl, request: "POST /?page=CiviCRM&q=civicrm/bsd/cons_action HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.akcjademokracja.pl"
commit: 346051bcb76c171ce8add6a1442f15b00f4249d8

data sent: 
{:action_name=>"trybunal", :external_id=>16, :action_type=>"petition", :action_technical_type=>"dzialaj.akcjademokracja.pl:petition", :create_at=>2015-12-03 13:41:54 UTC, :cons_hash=>{:firstname=>"MXXXX", :lastname=>"DXXXXX", :emails=>[{:email=>"YYYYYYY@interia.pl"}], :addresses=>[{:zip=>"QQ-408"}]}, :metadata=>{:sign_comment=>"Prawo jedno dla wszystkich bez względu na kolor skóry,wyznanie,pochodzenie jak i zajmowane stanowisko, też Prezydenta RP!", :sign_answer=>nil, :sign_boolean=>nil}}

**Comment by tttp** [comment]
Hi, 
it seems to be you are missing a standard class, what php version do you have? please upgrade ;)

https://github.com/WeMoveEU/speakcivi/blob/master/CRM/Speakcivi/Page/Speakcivi.php#L789

**Comment by lolownia** [comment]
```
php5 --version
PHP 5.6.15-1~dotdeb+7.1 (cli) (built: Nov  3 2015 16:29:58) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
www@lawenda-prod:~$ dpkg -l |grep php5
ii  libapache2-mod-php5             5.6.15-1~dotdeb+7.1           amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  newrelic-php5                   5.1.1.130                     amd64        The New Relic agent for PHP
ii  newrelic-php5-common            5.1.1.130                     all          Scripts and samples for the New Relic PHP agent
ii  php5                            5.6.15-1~dotdeb+7.1           all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-cli                        5.6.15-1~dotdeb+7.1           amd64        command-line interpreter for the php5 scripting language
ii  php5-common                     5.6.15-1~dotdeb+7.1           amd64        Common files for packages built from the php5 source
ii  php5-curl                       5.6.15-1~dotdeb+7.1           amd64        CURL module for php5
ii  php5-fpm                        5.6.15-1~dotdeb+7.1           amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php5-gd                         5.6.15-1~dotdeb+7.1           amd64        GD module for php5
ii  php5-mcrypt                     5.6.15-1~dotdeb+7.1           amd64        MCrypt module for php5
ii  php5-mysql                      5.6.15-1~dotdeb+7.1           amd64        MySQL module for php5
```
