### ISSUE TITLE
Set up On Hold Opt Out

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/speakcivi#81]
During setting up is_opt_out for contact entity, set up also on_hold = 2 and date for primary email.

**Comment by tttp** [comment]
Why?

**Comment by scardinius** [comment]
Because of database consistency with civicrm_contact.is_opt_out = 1

**Comment by tttp** [comment]
Is this how a "normal" optout does it? Still not sure why it matters/when we use this information

And we do way too many things synchronously to my taste already, can't we simply move that one to a sql that update civicrcm_email set on_hold=2 join civicrm_contact on c.id=email.contact_id and c.is_opt_out=1 where on_hold is null?

**Comment by scardinius** [comment]
Already not useful
