### ISSUE TITLE
link better the join and the petition signature

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/speakcivi#86]
We are already modifying the activity petition sign, to make it easier later to do more analysis:

- when creating the join activity, set the parent_id=petition sign id
- on the cleanup cronjob, set the join duration as = join date- petition date (if subject=confirmation_link)

**Comment by scardinius** [comment]
> when creating the join activity, set the parent_id=petition sign id

Done.

> on the cleanup cronjob...

this part requires other issue
